"""
Comprehensive test suite for all agents and orchestrator.

Tests:
1. File Agent - ZIP creation, file organization
2. Email Agent - Email composition
3. Presentation Agent - Keynote and Pages creation
4. Orchestrator - Complex multi-step workflows
5. Sub-agent coordination - Multiple agents working together
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import logging
from src.utils import load_config
from src.agent.agent_registry import AgentRegistry
from src.orchestrator.main_orchestrator import MainOrchestrator

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def test_file_agent_zip():
    """Test File Agent - ZIP creation."""
    logger.info("\n" + "="*80)
    logger.info("TEST 1: FILE AGENT - ZIP CREATION")
    logger.info("="*80)

    try:
        config = load_config()
        registry = AgentRegistry(config)
        file_agent = registry.get_agent("file")

        # Test creating a ZIP archive
        result = file_agent.execute("create_zip_archive", {
            "source_path": "test_docs",
            "zip_name": "test_docs_backup",
            "include_pattern": "*.pdf"
        })

        logger.info(f"\nZIP Creation Result:")
        logger.info(f"  Success: {not result.get('error', False)}")
        if not result.get('error'):
            logger.info(f"  ZIP Path: {result.get('zip_path')}")
            logger.info(f"  Files: {result.get('file_count')}")
            logger.info(f"  Size: {result.get('total_size')} bytes")
            logger.info(f"  Compressed: {result.get('compressed_size')} bytes")
            logger.info(f"  Compression: {result.get('compression_ratio')}%")
        else:
            logger.error(f"  Error: {result.get('error_message')}")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_file_agent_organize():
    """Test File Agent - File organization."""
    logger.info("\n" + "="*80)
    logger.info("TEST 2: FILE AGENT - FILE ORGANIZATION")
    logger.info("="*80)

    try:
        config = load_config()
        registry = AgentRegistry(config)
        file_agent = registry.get_agent("file")

        # Test organizing files by category
        result = file_agent.execute("organize_files", {
            "category": "AI and presentation documents",
            "target_folder": "ai_docs",
            "move_files": False  # Copy, don't move
        })

        logger.info(f"\nFile Organization Result:")
        logger.info(f"  Success: {result.get('success', False)}")
        if result.get('success'):
            logger.info(f"  Files organized: {len(result.get('files_moved', []))}")
            logger.info(f"  Files skipped: {len(result.get('files_skipped', []))}")
            logger.info(f"  Target path: {result.get('target_path')}")
            logger.info(f"  Total evaluated: {result.get('total_evaluated')}")

            # Show reasoning for first few files
            reasoning = result.get('reasoning', {})
            logger.info(f"\n  LLM Reasoning (first 3 files):")
            for i, (filename, reason) in enumerate(list(reasoning.items())[:3], 1):
                logger.info(f"    {i}. {filename}")
                logger.info(f"       → {reason}")
        else:
            logger.error(f"  Error: {result.get('error_message')}")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_email_agent():
    """Test Email Agent - Email composition."""
    logger.info("\n" + "="*80)
    logger.info("TEST 3: EMAIL AGENT - EMAIL COMPOSITION")
    logger.info("="*80)

    try:
        config = load_config()
        registry = AgentRegistry(config)
        email_agent = registry.get_agent("email")

        # Test composing an email (draft only)
        result = email_agent.execute("compose_email", {
            "subject": "Test Email - Auto Mac System",
            "body": """Hello,

This is a test email generated by the Auto Mac system.

The email agent successfully:
- Created the email draft
- Formatted the content
- Integrated with Mail.app

Best regards,
Auto Mac System""",
            "recipient": None,  # None = draft only
            "attachments": None,
            "send": False  # Don't send, just create draft
        })

        logger.info(f"\nEmail Composition Result:")
        logger.info(f"  Success: {not result.get('error', False)}")
        if not result.get('error'):
            logger.info(f"  Status: {result.get('status')}")
            logger.info(f"  Message: {result.get('message')}")
        else:
            logger.error(f"  Error: {result.get('error_message')}")
            logger.info(f"  Note: Email agent requires Mail.app on macOS")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_presentation_agent_keynote():
    """Test Presentation Agent - Keynote creation."""
    logger.info("\n" + "="*80)
    logger.info("TEST 4: PRESENTATION AGENT - KEYNOTE CREATION")
    logger.info("="*80)

    try:
        config = load_config()
        registry = AgentRegistry(config)
        presentation_agent = registry.get_agent("presentation")

        # Test creating a Keynote presentation
        result = presentation_agent.execute("create_keynote", {
            "title": "Auto Mac System Test",
            "content": """This is a test presentation created by the Auto Mac system.

The system demonstrates:

LLM-Driven Architecture
All decisions made by AI reasoning, no hardcoded logic.

Multi-Agent Coordination
Specialized agents work together seamlessly.

Task Automation
Complex workflows executed automatically.""",
            "output_path": None  # Use default location
        })

        logger.info(f"\nKeynote Creation Result:")
        logger.info(f"  Success: {not result.get('error', False)}")
        if not result.get('error'):
            logger.info(f"  Keynote path: {result.get('keynote_path')}")
            logger.info(f"  Slides: {result.get('slide_count')}")
            logger.info(f"  Message: {result.get('message')}")
        else:
            logger.error(f"  Error: {result.get('error_message')}")
            logger.info(f"  Note: Keynote creation requires Keynote.app on macOS")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_presentation_agent_pages():
    """Test Presentation Agent - Pages document creation."""
    logger.info("\n" + "="*80)
    logger.info("TEST 5: PRESENTATION AGENT - PAGES DOCUMENT")
    logger.info("="*80)

    try:
        config = load_config()
        registry = AgentRegistry(config)
        presentation_agent = registry.get_agent("presentation")

        # Test creating a Pages document
        result = presentation_agent.execute("create_pages_doc", {
            "title": "Auto Mac Test Report",
            "content": """Executive Summary

This report demonstrates the capabilities of the Auto Mac system.

System Architecture

The Auto Mac system uses a hierarchical multi-agent architecture:

1. Main Orchestrator - Coordinates all operations
2. Specialized Agents - Handle domain-specific tasks
3. LLM-Driven Decisions - All logic determined by AI

Key Features

- No hardcoded business logic
- Intelligent file organization
- Automated presentation creation
- Email integration
- Multi-step workflow execution

Conclusion

The system successfully demonstrates LLM-driven automation.""",
            "output_path": None
        })

        logger.info(f"\nPages Creation Result:")
        logger.info(f"  Success: {not result.get('error', False)}")
        if not result.get('error'):
            logger.info(f"  Pages path: {result.get('pages_path')}")
            logger.info(f"  Message: {result.get('message')}")
        else:
            logger.error(f"  Error: {result.get('error_message')}")
            logger.info(f"  Note: Pages creation requires Pages.app on macOS")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_orchestrator_simple():
    """Test Orchestrator - Simple workflow."""
    logger.info("\n" + "="*80)
    logger.info("TEST 6: ORCHESTRATOR - SIMPLE WORKFLOW")
    logger.info("="*80)

    try:
        config = load_config()
        orchestrator = MainOrchestrator(config, max_replans=1)

        # Test simple request
        result = orchestrator.execute(
            "Organize files in test_docs into categories using LLM reasoning"
        )

        logger.info(f"\nOrchestrator Result:")
        logger.info(f"  Success: {result.get('success', False)}")
        logger.info(f"  Status: {result.get('status')}")

        if result.get('success'):
            logger.info(f"  Steps completed: {len(result.get('step_results', []))}")

            # Show step results
            for i, step_result in enumerate(result.get('step_results', []), 1):
                logger.info(f"\n  Step {i}: {step_result.get('action')}")
                logger.info(f"    Status: {step_result.get('status')}")
                if step_result.get('result'):
                    output = step_result['result']
                    if isinstance(output, dict):
                        logger.info(f"    Output keys: {list(output.keys())}")
        else:
            logger.error(f"  Error: {result.get('error')}")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_orchestrator_complex():
    """Test Orchestrator - Complex multi-step workflow."""
    logger.info("\n" + "="*80)
    logger.info("TEST 7: ORCHESTRATOR - COMPLEX WORKFLOW")
    logger.info("="*80)

    try:
        config = load_config()
        orchestrator = MainOrchestrator(config, max_replans=2)

        # Test complex request involving multiple agents
        result = orchestrator.execute(
            "Find all PDF documents about AI in test_docs, create a ZIP archive of them, "
            "and create a summary presentation about what was archived"
        )

        logger.info(f"\nComplex Orchestrator Result:")
        logger.info(f"  Success: {result.get('success', False)}")
        logger.info(f"  Status: {result.get('status')}")

        if result.get('success'):
            logger.info(f"  Total steps: {len(result.get('step_results', []))}")

            # Show detailed step execution
            for i, step_result in enumerate(result.get('step_results', []), 1):
                logger.info(f"\n  Step {i}:")
                logger.info(f"    Action: {step_result.get('action')}")
                logger.info(f"    Status: {step_result.get('status')}")
                logger.info(f"    Agent: {step_result.get('agent', 'unknown')}")

                # Show key outputs
                if step_result.get('result') and isinstance(step_result['result'], dict):
                    result_data = step_result['result']
                    if 'zip_path' in result_data:
                        logger.info(f"    → Created ZIP: {result_data['zip_path']}")
                    if 'keynote_path' in result_data:
                        logger.info(f"    → Created Keynote: {result_data['keynote_path']}")
                    if 'files_moved' in result_data:
                        logger.info(f"    → Files processed: {len(result_data['files_moved'])}")
        else:
            logger.error(f"  Error: {result.get('error')}")
            logger.info(f"  This is expected if macOS apps aren't available")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def test_sub_agent_coordination():
    """Test sub-agent coordination through orchestrator."""
    logger.info("\n" + "="*80)
    logger.info("TEST 8: SUB-AGENT COORDINATION")
    logger.info("="*80)

    try:
        config = load_config()
        orchestrator = MainOrchestrator(config, max_replans=1)

        # Test request that requires multiple agents working together
        result = orchestrator.execute(
            "Search for documents about presentations in test_docs, "
            "organize them into a folder, create a ZIP of that folder, "
            "and draft an email summarizing what was organized"
        )

        logger.info(f"\nSub-Agent Coordination Result:")
        logger.info(f"  Success: {result.get('success', False)}")

        if result.get('success'):
            # Identify which agents were used
            agents_used = set()
            for step_result in result.get('step_results', []):
                action = step_result.get('action', '')
                # Determine agent from action name
                if 'search_documents' in action or 'organize_files' in action or 'create_zip' in action:
                    agents_used.add('file_agent')
                if 'compose_email' in action:
                    agents_used.add('email_agent')
                if 'create_keynote' in action or 'create_pages' in action:
                    agents_used.add('presentation_agent')

            logger.info(f"  Agents coordinated: {', '.join(agents_used)}")
            logger.info(f"  Steps executed: {len(result.get('step_results', []))}")

            # Show coordination flow
            logger.info(f"\n  Execution Flow:")
            for i, step_result in enumerate(result.get('step_results', []), 1):
                logger.info(f"    {i}. {step_result.get('action')} - {step_result.get('status')}")
        else:
            logger.error(f"  Error: {result.get('error')}")

        return result

    except Exception as e:
        logger.error(f"Test failed: {e}", exc_info=True)
        return {"error": True, "error_message": str(e)}


def run_all_tests():
    """Run all tests and generate summary."""
    logger.info("\n" + "="*80)
    logger.info("COMPREHENSIVE AGENT AND ORCHESTRATOR TESTS")
    logger.info("="*80)

    tests = [
        ("File Agent - ZIP", test_file_agent_zip),
        ("File Agent - Organize", test_file_agent_organize),
        ("Email Agent", test_email_agent),
        ("Presentation - Keynote", test_presentation_agent_keynote),
        ("Presentation - Pages", test_presentation_agent_pages),
        ("Orchestrator - Simple", test_orchestrator_simple),
        ("Orchestrator - Complex", test_orchestrator_complex),
        ("Sub-Agent Coordination", test_sub_agent_coordination),
    ]

    results = {}
    for test_name, test_func in tests:
        try:
            result = test_func()
            results[test_name] = {
                "success": not result.get('error', False),
                "result": result
            }
        except Exception as e:
            logger.error(f"Test {test_name} crashed: {e}")
            results[test_name] = {
                "success": False,
                "error": str(e)
            }

    # Print summary
    logger.info("\n" + "="*80)
    logger.info("TEST SUMMARY")
    logger.info("="*80)

    passed = sum(1 for r in results.values() if r['success'])
    total = len(results)

    for test_name, result in results.items():
        status = "✓ PASS" if result['success'] else "✗ FAIL"
        logger.info(f"  {status} - {test_name}")

    logger.info(f"\nTotal: {passed}/{total} tests passed ({int(passed/total*100)}%)")

    # Additional notes
    logger.info("\n" + "="*80)
    logger.info("NOTES:")
    logger.info("="*80)
    logger.info("  - Email and Presentation tests require macOS with Mail.app/Keynote/Pages")
    logger.info("  - File operations should work on any platform")
    logger.info("  - All agents use LLM-driven decision making")
    logger.info("  - Complex workflows demonstrate multi-agent coordination")

    return results


if __name__ == "__main__":
    run_all_tests()
