# Cerebro OS API Specification
# This is the human-facing API documentation that should stay in sync with api_server.py
# The Oqoqo self-evolving docs system will detect drift between this spec and the actual code

openapi: "3.0.3"
info:
  title: Cerebro OS API
  description: |
    REST and WebSocket API for Cerebro OS - an intelligent Mac automation assistant.
    This specification documents the public API endpoints available for integration.
  version: "1.0.0"
  contact:
    name: Cerebro OS
    
servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: Health
    description: Health check and status endpoints
  - name: Chat
    description: Chat and conversation endpoints
  - name: Commands
    description: Command listing and execution
  - name: Agents
    description: Agent information and capabilities
  - name: Config
    description: Configuration management
  - name: Spotify
    description: Spotify playback control
  - name: Files
    description: File and document operations

paths: {}

components:
  schemas:
    SystemStats:
      type: object
      properties:
        indexed_documents:
          type: integer
          description: Number of indexed documents
        total_chunks:
          type: integer
          description: Total document chunks
        available_agents:
          type: array
          items:
            type: string
          description: List of available agent names
        uptime:
          type: string
          description: Service uptime status

    ChatMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: User message to process
        session_id:
          type: string
          description: Optional session ID for context

    ChatResponse:
      type: object
      properties:
        response:
          type: string
          description: Assistant response
        status:
          type: string
          description: Response status (completed, error, etc.)
        timestamp:
          type: string
          format: date-time
          description: Response timestamp

    AgentInfo:
      type: object
      properties:
        name:
          type: string
          description: Agent name
        description:
          type: string
          description: Agent description
        tools:
          type: array
          items:
            type: string
          description: Available tools

    Command:
      type: object
      properties:
        id:
          type: string
          description: Command identifier
        title:
          type: string
          description: Display title
        description:
          type: string
          description: Command description
        category:
          type: string
          description: Command category
        icon:
          type: string
          description: Emoji icon
        keywords:
          type: array
          items:
            type: string
          description: Search keywords
        handler_type:
          type: string
          description: Handler type (agent, slash_command, etc.)

    SpotifyStatus:
      type: object
      properties:
        is_playing:
          type: boolean
          description: Whether music is currently playing
        item:
          type: object
          properties:
            name:
              type: string
              description: Track name
            artists:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
            album:
              type: object
              properties:
                name:
                  type: string
                images:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
            duration_ms:
              type: integer
        progress_ms:
          type: integer
          description: Current playback position in milliseconds
        device:
          type: object
          properties:
            name:
              type: string
            type:
              type: string